kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: prometheus-k8s
 namespace: apisix-test
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
roleRef:
 kind: Role
 name: prometheus-k8s
 apiGroup: rbac.authorization.k8s.io
